### ISSUE TITLE
"Dispozitive disponibile" | 14.0.5.0 Stable

### ISSUE THREAD

**Issue by AstroNoot** [ashtefan/Romanian_MIUI_14#1]
String-ul "Dispozitive disponibile" din meniul bluetooth e all caps.

![Screenshot_2023-03-19-11-39-53-209_com android settings](https://user-images.githubusercontent.com/38353543/226166516-da19d515-7577-45fd-aa64-b59bc12a6c7b.jpg)

**Comment by ashtefan** [comment]
Așa este și în limba engleză, deci nu e problemă de traducere.
